### ISSUE TITLE
Sign Group Contract

### ISSUE THREAD

**Issue by neelay-j** [cse110-fa22-group28/cse110-fa22-group28#2]
**Is your feature request related to a problem? Please describe.**
Once @Arisan39 and/or @ojeengammah have set up the group contract, we each need to sign the contract. This is also due by Sunday 10/16.

**Describe the solution you'd like**
IN A NEW BRANCH, copy the group contract, `admin/misc/rules.md`, and **create new PDF file** titled `admin/misc/rules-yourname.pdf` (e.g. `admin/misc/rules-neelayjoglekar.pdf`). Add your signature at the bottom of this page. Submit a PR request associated with this issue.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ojeengammah** [comment]
![signature](https://user-images.githubusercontent.com/82119065/195993819-6784c4dd-e93b-4d94-a7bc-39d30e08f8fa.png)
