### ISSUE TITLE
CI/CD Phase 1 - Linting and Code Validation

### ISSUE THREAD

**Issue by yashpuneet** [cse110-fa22-group28/cse110-fa22-group28#79]
# Administrative or Organizational Tasks

What is the purpose of this task?

Start designing and building the CI/CD Pipeline for our project. In this phase, we will primarily build the document consistency and clarity tests using linting for markdown and format/style validation for HTML, CSS, and JS files. 

Steps to complete the task:
- [x] Research various validation and lining APIs to determine whether it makes sense to use one that is already available or create custom listing scripts
- [x] Write an ADR document with the choice defined after the research above
- [x] Implement the Validation Github action set to run after every commit
- [x] Generate logs for all errors to make linter outputs more readable. Include only errors and warnings as they are the only relevant parts that need to be edited to pass linting. The info and text-based graphics should not be included in error logs to make them shorter and more manageable.

Useful Resources:
- Canvas Assignment: https://canvas.ucsd.edu/courses/39754/assignments/526058

**Comment by ojeengammah** [comment]
Vaughan and I have already create a ci pipeline for linting as well as code validation
