### ISSUE TITLE
MVP Deployment

### ISSUE THREAD

**Issue by yashpuneet** [cse110-fa22-group28/cse110-fa22-group28#80]
# Administrative or Organizational Tasks

What is the purpose of this task?

To stitch all the individual parts of the MVP together to prepare an initial version for deployment and the team-status presentation. We have an initial page deployed on Netlfy already and this has been added to our CI/CD pipeline (pushes to main get automatically deployed to Netlify). This task ensures that all work completed in the MVP creation for Sprint 2 is compatible and works well together for our initial MVP deployment.

Steps to complete the task:
- [ ] Complete all cleanup and check issues before working on this task 
    - [x] #99 
    - [x] #100 
- [ ] Complete the Initial unit testing issue and ensure all these basic unit tests pass before attempting deployment
    - [ ] #103 
- [x] Manually review sub-team code to check for variable inconsistencies if they exist (manual compatibility testing)
- [ ] Add paths to files to link them together to allow them to work together and put the parts together to have a functioning application
- [x] Test locally for basic input and saving functionality errors if they exist 
    - [ ] write integration unit tests to ensure that putting the parts together didn't break anything
    - [x] perform manual click-through test (automation with Puppeteer can be completed later)
- [x] Merge completed dev branch to main to trigger a deployment to Netlify
- [x] Perform manual click through testing on the web-deployed version

**Comment by neelay-j** [comment]
Although automated tests are yet to be implemented, MVP has been deployed and performs well with basic functionalities. Making the app robust to edge cases and formalizing testing + more documentation is necessary
