### ISSUE TITLE
Chore Card: Linting Fixes

### ISSUE THREAD

**Issue by yashpuneet** [cse110-fa22-group28/cse110-fa22-group28#87]
# Administrative or Organizational Tasks

What is the purpose of this task?

To fix linting errors in the chore card file in order to improve code format consistency and readability.

Steps to complete the task:
- [x] HTML

- [x] CSS
1:1   ✖  Unexpected empty line                        no-empty-first-line                               
  2:1   ✖  Expected no more than 1 empty line           max-empty-lines                                   
  4:1   ✖  Expected indentation of 2 spaces             indentation                                       
  5:1   ✖  Expected indentation of 2 spaces             indentation                                       
  6:1   ✖  Expected indentation of 2 spaces             indentation                                       
  8:1   ✖  Unexpected empty line before declaration     declaration-empty-line-before                     
  8:1   ✖  Expected indentation of 2 spaces             indentation                                       
  9:1   ✖  Expected indentation of 2 spaces             indentation                                       
 10:5   ✖  Expected double quotes                       string-quotes                                     
 11:5   ✖  Expected double quotes                       string-quotes                                     
 12:5   ✖  Expected double quotes                       string-quotes                                     
 13:1   ✖  Expected indentation of 2 spaces             indentation                                       
 14:1   ✖  Expected shorthand property "grid-template"  declaration-block-no-redundant-longhand-properties
 14:1   ✖  Expected indentation of 2 spaces             indentation                                       
 15:1   ✖  Expected indentation of 2 spaces             indentation                                       
 16:1   ✖  Expected indentation of 2 spaces             indentation                                       
 16:19  ✖  Expected "#2196F3" to be "#2196f3"           color-hex-case                                    
 17:1   ✖  Expected indentation of 2 spaces             indentation                                       
 21:1   ✖  Expected indentation of 2 spaces             indentation                                       
 21:19  ✖  Expected modern color-function notation      color-function-notation                           
 21:[39](https://github.com/cse110-fa22-group28/cse110-fa22-group28/actions/runs/3502677739/jobs/5867224361#step:4:40)  ✖  Expected "0.8" to be "80%"                   alpha-value-notation                              
 22:1   ✖  Expected indentation of 2 spaces             indentation                                       
 23:1   ✖  Expected indentation of 2 spaces             indentation                                       
 24:1   ✖  Expected indentation of 2 spaces             indentation                                       
 28:1   ✖  Expected indentation of 2 spaces             indentation                                       
 29:1   ✖  Expected indentation of 2 spaces             indentation                                       
 30:1   ✖  Expected indentation of 2 spaces             indentation                                       
 31:1   ✖  Expected indentation of 2 spaces             indentation                                       
 35:1   ✖  Expected indentation of 2 spaces             indentation                                       
 39:1   ✖  Expected indentation of 2 spaces             indentation                                       
 43:1   ✖  Expected indentation of 2 spaces             indentation                                       
 47:1   ✖  Expected indentation of 2 spaces             indentation                                       
 48:1   ✖  Expected indentation of 2 spaces             indentation                                       
 49:1   ✖  Expected indentation of 2 spaces             indentation                                       
 50:1   ✖  Expected indentation of 2 spaces             indentation                                       
 54:1   ✖  Expected indentation of 2 spaces             indentation                                       
 55:1   ✖  Expected indentation of 2 spaces             indentation                                       
 56:1   ✖  Expected indentation of 2 spaces             indentation                                       
 60:1   ✖  Expected indentation of 2 spaces             indentation                                       
 61:1   ✖  Expected indentation of 2 spaces             indentation

**Comment by neelay-j** [comment]
All css and html linting errors fixed in #121
